require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'Covid19' do

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'Covid19Tests' do
    inherit! :complete
    # Pods for testing
  end
  
  use_unimodules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Covid19-tvOS' do
  # Pods for Covid19-tvOS

  target 'Covid19-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
